import { expect, test } from '@playwright/test';
import type { Exercise } from '@aide/shared';
import { ensureChild, importDocument, openBooksAs, openParentArea, readLocalTable, signIn, trackPageErrors } from './support/app';
import { makeTextPdf } from './support/fixtures';

const CHILD = 'Léa';

test('parent area: every page opens, settings persist on the server, a glossary word reaches the reader', async ({ page, browser }) => {
  const pageErrors = trackPageErrors(page);
  await signIn(page);
  await ensureChild(page, CHILD);

  await test.step('AI and privacy settings are saved on the server', async () => {
    await openParentArea(page, 'ia');
    const deep = page.getByRole('switch', { name: /Réponses approfondies aux questions sur le texte/ });
    await expect(deep).toHaveAttribute('aria-checked', 'false');
    await deep.click();
    await page.getByRole('button', { name: 'Enregistrer' }).click();
    await expect(page.getByText('Réglages enregistrés.')).toBeVisible();
    const res = await page.request.get('/api/settings');
    expect(((await res.json()) as { ai: { deepQuestions: boolean } }).ai.deepQuestions).toBe(true);
    await page.reload();
    await expect(page.getByRole('switch', { name: /Réponses approfondies aux questions sur le texte/ })).toHaveAttribute('aria-checked', 'true');
  });

  await test.step('the other parent pages open', async () => {
    for (const [path, heading] of [
      ['documents', 'Livres et documents'],
      ['activite', 'Activité'],
      ['synchronisation', 'Synchronisation'],
      ['compte', 'Compte'],
      ['glossaire', 'Glossaire'],
    ] as const) {
      await openParentArea(page, path);
      await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible();
    }
  });

  await test.step('the parent adds a glossary word', async () => {
    await page.getByRole('button', { name: 'Ajouter un mot' }).first().click();
    const sheet = page.getByRole('dialog');
    await sheet.getByLabel('Mot', { exact: true }).fill('carnet');
    await sheet.getByLabel('Définition pour l’enfant').fill('Petit cahier où l’on écrit ce qu’on veut garder en mémoire.');
    await sheet.getByRole('button', { name: 'Enregistrer' }).click();
    await expect(page.getByText('Mot enregistré.')).toBeVisible();
    await expect(page.getByRole('listitem').filter({ hasText: 'Petit cahier où l’on écrit' })).toContainText('carnet');
  });

  await test.step('📖 Définition uses the parent glossary first', async () => {
    const pdf = await makeTextPdf(browser);
    await importDocument(page, 'Glossaire – Le volcan', [{ name: 'volcan.pdf', mimeType: 'application/pdf', buffer: pdf }], 2);
    await openBooksAs(page, CHILD);
    await page.getByRole('button', { name: /Glossaire – Le volcan/ }).first().click();
    const word = page.locator('.rp-page[data-page-index="0"] .rp-w', { hasText: /^carnet$/ }).first();
    await word.tap();
    await page.getByRole('button', { name: /Définition/ }).click();
    await expect(page.getByRole('dialog')).toContainText('Petit cahier où l’on écrit ce qu’on veut garder en mémoire.');
  });

  expect(pageErrors).toEqual([]);
});

test('help service: progressive summary and AI questions go through asynchronous jobs', async ({ page, browser }) => {
  const pageErrors = trackPageErrors(page);
  const book = 'Jobs – Le volcan';
  await signIn(page);
  await ensureChild(page, CHILD);
  const pdf = await makeTextPdf(browser);
  await importDocument(page, book, [{ name: 'jobs.pdf', mimeType: 'application/pdf', buffer: pdf }], 2);
  await expect(page.locator('li', { hasText: book })).toContainText('Prêt', { timeout: 30_000 });
  await openBooksAs(page, CHILD);

  await test.step('📝 summary: chunk requests, then the final stage as a job', async () => {
    const jobs: number[] = [];
    page.on('response', (r) => {
      if (r.url().includes('/api/ai/summarize') && r.request().method() === 'POST') jobs.push(r.status());
    });
    await page.goto('/exercices');
    await page.getByRole('button', { name: new RegExp(book) }).first().click();
    await page.getByRole('link', { name: /Résumé/ }).or(page.getByRole('button', { name: /Résumé/ })).first().click();
    await page.getByRole('button', { name: /Faire le résumé/ }).click();
    await expect(page.getByRole('heading', { name: /Le résumé/ })).toBeVisible({ timeout: 60_000 });
    await expect(page.getByText('Résumé préparé sans aide en ligne')).toBeHidden();
    expect(jobs).toContain(200);
    expect(jobs).toContain(202);
  });

  await test.step('🧠 questions generated by the help service (job + polling)', async () => {
    const polled = page.waitForResponse((r) => r.url().includes('/api/ai/jobs/'), { timeout: 60_000 });
    await page.goto('/exercices');
    await page.getByRole('button', { name: new RegExp(book) }).first().click();
    await page.getByRole('link', { name: /Fais-moi des questions/ }).or(page.getByRole('button', { name: /Fais-moi des questions/ })).first().click();
    await page.getByRole('button', { name: /C’est parti/ }).click();
    await polled;
    await page.waitForURL(/\/exercices\/quiz\//, { timeout: 60_000 });
    const exerciseId = decodeURIComponent(new URL(page.url()).pathname.split('/').pop() ?? '');
    const exercise = (await readLocalTable<Exercise>(page, 'exercises')).find((e) => e.id === exerciseId);
    expect(exercise?.origin).toBe('ai');
    expect(exercise?.questions.length ?? 0).toBeGreaterThan(0);
    await expect(page.getByText(/Question 1 sur/)).toBeVisible();
    await expect(page.getByText('Questions préparées sans aide en ligne')).toBeHidden();
  });

  await test.step('the parent sees these requests in Activité', async () => {
    await openParentArea(page, 'activite');
    const aiSection = page.getByRole('region', { name: 'Demandes d’aide intelligente' }).or(page.locator('section', { hasText: 'Demandes d’aide intelligente' })).first();
    await expect(aiSection).toContainText(/\d+ demandes/);
    await expect(aiSection).not.toContainText('Aucune demande sur la période.');
  });

  expect(pageErrors).toEqual([]);
});
