// French word list (public/data/mots-fr.txt, generated by scripts/copy-assets.mjs), loaded lazily.
// The file is sorted and normalized: lookups are binary searches on the raw text, which keeps memory low on iPad.
import type { WordList } from '@aide/shared';

export const WORD_LIST_URL = '/data/mots-fr.txt';

/** WordList over newline-separated, sorted (UTF-16 order), unique normalized words. */
export function createSortedWordList(raw: string): WordList {
  const text = raw.replace(/\r/g, '');
  const starts: number[] = [];
  let pos = 0;
  while (pos < text.length) {
    const end = text.indexOf('\n', pos);
    const stop = end === -1 ? text.length : end;
    if (stop > pos) starts.push(pos);
    pos = stop + 1;
  }
  const offsets = Int32Array.from(starts);
  const wordAt = (i: number): string => {
    const start = offsets[i]!;
    const end = text.indexOf('\n', start);
    return text.slice(start, end === -1 ? text.length : end);
  };
  return {
    size: offsets.length,
    has(normalizedWord: string): boolean {
      if (normalizedWord.length === 0) return false;
      let lo = 0;
      let hi = offsets.length - 1;
      while (lo <= hi) {
        const mid = (lo + hi) >> 1;
        const word = wordAt(mid);
        if (word === normalizedWord) return true;
        if (word < normalizedWord) lo = mid + 1;
        else hi = mid - 1;
      }
      return false;
    },
  };
}

let cached: Promise<WordList | null> | null = null;

/** Loads the list once; resolves null when unavailable (offline before caching…), and retries on a later call. */
export function loadFrenchWordList(fetchImpl: typeof fetch = fetch): Promise<WordList | null> {
  if (cached) return cached;
  const attempt = (async (): Promise<WordList | null> => {
    try {
      const res = await fetchImpl(WORD_LIST_URL, { credentials: 'same-origin' });
      if (!res.ok) return null;
      const list = createSortedWordList(await res.text());
      return list.size > 0 ? list : null;
    } catch {
      return null;
    }
  })();
  cached = attempt;
  void attempt.then((list) => {
    if (list === null && cached === attempt) cached = null;
  });
  return attempt;
}

/** Test helper. */
export function resetWordListCache(): void {
  cached = null;
}
